---
- name: Install AnyDesk.
  tags: anydesk
  block:
    - name: Add AnyDesk repository.
      ansible.builtin.yum_repository:
        name: anydesk
        description: AnyDesk Fedora - stable
        baseurl: http://rpm.anydesk.com/fedora/$releasever/$basearch/
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: https://keys.anydesk.com/repos/RPM-GPG-KEY
        enabled: true

    - name: Install AnyDesk. # noqa: package-latest
      ansible.builtin.dnf:
        name: anydesk
        state: latest
        update_cache: true
