---
- name: Install balenaEtcher
  tags: balena-etcher
  block:
    - name: Download balenaEtcher RPM
      ansible.builtin.get_url:
        url: "https://github.com/balena-io/etcher/releases/download/v{{ balena_etcher_version }}/balena-etcher-{{ balena_etcher_version }}-1.x86_64.rpm"
        dest: "/root/balena-etcher-{{ balena_etcher_version }}-1.x86_64.rpm"
        mode: "0644"

    - name: Install balenaEtcher RPM
      ansible.builtin.dnf:
        name: "/root/balena-etcher-{{ balena_etcher_version }}-1.x86_64.rpm"
        state: present
        disable_gpg_check: true
