---
- name: Configure .bashrc
  tags: rc
  block:
    - name: Remove obsolete git branch PS1 hack
      ansible.builtin.blockinfile:
        path: /home/{{ username }}/.bashrc
        block: |
          parse_git_branch() {
            git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
          }
          PS1=`echo $PS1 | sed "s/..$/\\$(parse_git_branch)$ /"`
        state: absent

    - name: Add RedHat developer credentials to .bashrc
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.bashrc
        line: "{{ item }}"
      loop:
        - export RH_USER={{ redhat_developer_user }}
        - export RH_PASS={{ redhat_developer_password }}
      no_log: true

    - name: Add Cargo bin to PATH
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.bashrc
        line: export PATH="$HOME/.cargo/bin:$PATH"
        state: present

    - name: Add KUBECONFIG environment variable
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.bashrc
        line: export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        state: present

    - name: Add aliases
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.bashrc
        line: "{{ item }}"
      loop:
        - alias ll='ls -alF'
        - alias pandoc='docker run --rm -v "$(pwd):/data" -u $(id -u):$(id -g) pandoc/latex'
        - alias sizeof='du -sh'
        - 'ds() { if [ -z "$1" ]; then echo "Usage: ds <docker-image>"; return 1; fi; docker run --rm -it -v "$(pwd):/data" "$1" /bin/bash; }'
        - alias ssh-fitpc='ssh -t sam@sydneystraat.duckdns.org -p 27372 byobu'
        - alias ssh-cubi='ssh -t sam@cubi byobu'
        - alias ssh-liteserver='ssh -t '
        - alias activate-ansible='. ~/python3-venv/ansible-latest/bin/activate && ansible --version'
