---
- name: Install BetterBird
  tags: betterbird
  block:
    - name: Install Proton Mail Bridge
      ansible.builtin.apt:
        deb: https://proton.me/download/bridge/protonmail-bridge_3.21.2-1_amd64.deb

    - name: Ensure /opt/betterbird directory exists
      ansible.builtin.file:
        path: "/opt/betterbird"
        state: directory
        mode: '0755'

    - name: Get latest BetterBird download URL
      ansible.builtin.uri:
        url: https://www.betterbird.eu/downloads/getloc.php?os=lin&lang=en-US&version=release
        return_content: true
      register: uri_result

    - name: Extract BetterBird
      ansible.builtin.unarchive:
        src: "{{ uri_result.content | trim }}"
        dest: /opt/
        creates: /opt/betterbird/betterbird
        remote_src: true

    - name: Create symbolic link for betterbird binary
      ansible.builtin.file:
        src: "/opt/betterbird/betterbird"
        dest: "/usr/bin/betterbird"
        state: link

    - name: Download icon
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Betterbird/thunderbird-patches/main/metadata/icons/betterbird256.png
        dest: /home/{{ username }}/.local/share/icons/betterbird.icon
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0644"

    - name: Create desktop entry for BetterBird
      ansible.builtin.copy:
        dest: /home/{{ username }}/.local/share/applications/betterbird.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=BetterBird
          Comment=Email client
          Exec=/usr/bin/betterbird
          Icon=/home/{{ username }}/.local/share/icons/betterbird.icon
          Terminal=false
          Categories=Network;Email;
        mode: "0644"
