---
- name: Install draw.io desktop app
  tags: drawio
  block:
    - name: Get the redirect location from GitHub latest release URL
      ansible.builtin.uri:
        url: "https://github.com/jgraph/drawio-desktop/releases/latest"
        method: HEAD
        follow_redirects: none
        status_code: 302
      register: uri_result

    - name: Extract version from the URL
      ansible.builtin.set_fact:
        drawio_version: "{{ uri_result.location | regex_search('tag/v([0-9.]+)', '\\1') | first }}"

    - name: Check if version is already installed
      ansible.builtin.shell:
        cmd: dpkg -l | grep draw.io | grep "{{ drawio_version }}"
      ignore_errors: true
      failed_when: false
      changed_when: false
      register: dpkg_result

    - name: Create download URL
      ansible.builtin.set_fact:
        download_url: https://github.com/jgraph/drawio-desktop/releases/download/v{{ drawio_version }}/drawio-amd64-{{ drawio_version }}.deb

    - name: Install deb file
      ansible.builtin.apt:
        deb: "{{ download_url }}"
