---
- name: Configure Dropbox
  tags: dropbox
  block:
    - name: Make sure Dropbox can monitor all files and node works properly (1)
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: "^fs\\.inotify\\.max_user_watches="
        line: fs.inotify.max_user_watches=524288
        state: present
      notify: Reload sysctl config

    - name: Make sure Dropbox can monitor all files and node works properly (2)
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: "^fs\\.inotify\\.max_user_instances="
        line: fs.inotify.max_user_instances=512
        state: present
      notify: Reload sysctl config
