---
- name: Configure GRUB kernel arguments
  tags: grub
  block:
    - name: Get current kernel arguments
      ansible.builtin.command: grubby --info=ALL
      register: grubby_info
      changed_when: false

    - name: Set acpi.ec_no_wakeup=1 kernel argument
      ansible.builtin.command: grubby --update-kernel=ALL --args="acpi.ec_no_wakeup=1"
      when: '"acpi.ec_no_wakeup=1" not in grubby_info.stdout'
      changed_when: true
