---
- name: Configure hibernate
  tags: hibernate
  block:
    - name: Enable hibernate
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regex: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - regex: "^.*HandleSuspendKey\\s*=.*$"
          line: HandleSuspendKey=hibernate
        - regex: "^.*HandleLidSwitch\\s*=.*$"
          line: HandleLidSwitch=hibernate
      notify: Restart systemd-logind
      tags: hibernate

    - name: Enable sudo-less hibernate
      ansible.builtin.copy:
        dest: /etc/polkit-1/rules.d/85-hibernate.rules
        content: |
          polkit.addRule(function(action, subject) {
              if (action.id == "org.freedesktop.login1.hibernate" &&
                  subject.isInGroup("sudo")) {
                  return polkit.Result.YES;
              }
          });
        owner: root
        group: root
        mode: "0644"
      tags: hibernate
