---
- name: Configure hibernate
  tags: hibernate
  block:
    - name: Create logind.conf.d directory
      ansible.builtin.file:
        path: /etc/systemd/logind.conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Enable hibernate
      ansible.builtin.copy:
        dest: /etc/systemd/logind.conf.d/hibernate.conf
        content: |
          [Login]
          HandleSuspendKey=hibernate
          HandleLidSwitch=hibernate
        owner: root
        group: root
        mode: "0644"
      notify: Restart systemd-logind

    - name: Enable sudo-less hibernate
      ansible.builtin.copy:
        dest: /etc/polkit-1/rules.d/85-hibernate.rules
        content: |
          polkit.addRule(function(action, subject) {
              if (action.id == "org.freedesktop.login1.hibernate" &&
                  subject.isInGroup("wheel")) {
                  return polkit.Result.YES;
              }
          });
        owner: root
        group: root
        mode: "0644"
