---

- name: Install InSpec
  tags: inspec
  block:
    - name: Install InSpec
      ansible.builtin.apt:
        deb: https://packages.chef.io/files/stable/inspec/4.52.9/ubuntu/20.04/inspec_4.52.9-1_amd64.deb
        state: present

    - name: Install ruby-dev
      ansible.builtin.apt:
        name: ruby-dev
