---
- name: Install Node.js
  tags: nodejs
  block:
    - name: Add NodeSource repository
      ansible.builtin.get_url:
        url: https://rpm.nodesource.com/setup_20.x
        dest: /tmp/nodesource_setup.sh
        mode: '0755'

    - name: Run NodeSource setup script
      ansible.builtin.command:
        cmd: bash /tmp/nodesource_setup.sh
        creates: /etc/yum.repos.d/nodesource-nodejs.repo

    - name: Install Node.js
      ansible.builtin.dnf: # noqa: package-latest
        name: nodejs
        state: latest

    - name: Install TypeScript (needed to transpile .ts to .js)
      community.general.npm:
        name: typescript
        global: true
        state: present

    - name: Install VSCE (needed to publish vscode extensions)
      ansible.builtin.command:
        cmd: npm install -g @vscode/vsce
        creates: /usr/lib/node_modules/@vscode/vsce
