---
- name: Install NVIDIA driver
  tags: nvidia
  block:
    - name: Check for NVIDIA GPU
      ansible.builtin.command: lspci
      register: nvidia_check_result
      changed_when: false

    - name: Install and configure NVIDIA driver (to prevent nouveau driver crashes)
      when: "'nvidia' in nvidia_check_result.stdout | lower"
      block:
        - name: Enable RPMFusion non-free repository
          ansible.builtin.dnf:
            name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{
              ansible_distribution_major_version }}.noarch.rpm"
            state: present
            disable_gpg_check: true

        - name: Install akmod-nvidia
          ansible.builtin.dnf:
            name:
              - akmod-nvidia
              - xorg-x11-drv-nvidia-cuda
            state: present
          register: akmod_install_result

        - name: Build NVIDIA kernel module and rebuild initramfs
          when: akmod_install_result.changed
          block:
            - name: Build NVIDIA kernel module
              ansible.builtin.command: akmods --force
              changed_when: true

            - name: Rebuild initramfs
              ansible.builtin.command: dracut --force
              changed_when: true
