---
- name: Install PrusaSlicer
  tags: prusa
  block:
    - name: Install Flatpak
      ansible.builtin.apt:
        name: flatpak
        state: present

    - name: Add Flathub Repository
      ansible.builtin.command:
        cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        creates: /var/lib/flatpak/repo/flathub.trustedkeys.gpg

    - name: Install PrusaSlicer using flatpak
      community.general.flatpak:
        name: com.prusa3d.PrusaSlicer
        state: present
