---
- name: Install Visual Studio Code and related tools
  tags: vscode
  block:
    - name: Add VS Code repository
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/yumrepos/vscode/repodata/repomd.xml.key
        dest: /etc/pki/rpm-gpg/microsoft-vscode.asc
        mode: '0644'

    - name: Add VS Code repo file
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/microsoft-vscode.asc
        mode: '0644'

    - name: Install VS Code
      ansible.builtin.dnf:
        name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('-' + visual_studio_code_version, '') }}"
        state: present

    - name: Install VS Code extensions
      become: true
      become_user: "{{ username }}"
      ansible.builtin.command:
        cmd: code --install-extension {{ item }}
        creates: /home/{{ username }}/.vscode/extensions/{{ item }}-*/*.md
      loop:
        - redhat.ansible
        - redhat.vscode-yaml
        - yzhang.markdown-all-in-one
        - mhutchie.git-graph
        - ms-dotnettools.csdevkit
        - ms-vscode-remote.remote-ssh
        - ms-vscode-remote.remote-containers
        - ms-vscode.cpptools-extension-pack
        - ms-vscode.cmake-tools
        - ms-python.python
        - blauwelucht.ansible-go-to-definition
        - rust-lang.rust-analyzer
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - hediet.vscode-drawio
        - edgardmessias.clipboard-manager
        - dbaeumer.vscode-eslint
        - davidanson.vscode-markdownlint
        - bierner.markdown-mermaid
        - docker.docker
        - tomoki1207.pdf
        - platformio.platformio-ide
        - github.vscode-github-actions

    - name: Create config directories
      ansible.builtin.file:
        state: directory
        path: /home/{{ username }}/.config/Code/User/{{ item }}
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0775"
      loop:
        - snippets

    - name: Copy configuration files
      ansible.builtin.template:
        src: vscode/{{ item }}
        dest: /home/{{ username }}/.config/Code/User/{{ item }}
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0664"
      loop:
        - keybindings.json
        - settings.json
        - snippets/csharp.json

    - name: Add Microsoft prod repository
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/rhel/9/prod.repo
        dest: /etc/yum.repos.d/microsoft-prod.repo
        mode: '0644'

    - name: Exclude azure-cli from Microsoft prod repo (use Fedora native package instead)
      ansible.builtin.lineinfile:
        path: /etc/yum.repos.d/microsoft-prod.repo
        insertafter: '^\[packages-microsoft-com-prod\]'
        regexp: '^excludepkgs='
        line: 'excludepkgs=azure-cli'

    - name: Install PowerShell
      ansible.builtin.dnf:
        name: powershell
        state: present

    - name: Install .NET SDK
      ansible.builtin.dnf: # noqa package-latest
        name:
          - dotnet-runtime-8.0
          - dotnet-sdk-8.0
          - aspnetcore-runtime-8.0
        state: latest

    - name: Add DOTNET_ROOT to .bashrc
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.bashrc
        line: export DOTNET_ROOT=/usr/share/dotnet

    # Prevent Ctrl-. from being stolen by IBus:
    - name: Check if org.freedesktop.ibus.general.hotkey triggers is set
      become: true
      become_user: "{{ username }}"
      ansible.builtin.command: gsettings get org.freedesktop.ibus.panel.emoji hotkey
      changed_when: false
      register: gsettings_result

    - name: Disable Ctrl-. binding for emoji in IBus if set
      become: true
      become_user: "{{ username }}"
      ansible.builtin.command: gsettings set org.freedesktop.ibus.panel.emoji hotkey "['']"
      changed_when: true
      when:
        - gsettings_result.stdout != "['']"
